create schema fpe;
use fpe;

CREATE TABLE `MODELO_PREVISAO` (
  `IDT_MODELO` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `DSC_MODELO` VARCHAR(40)
);

CREATE TABLE `PERIODO_PREVISAO` (
  `IDT_PERIODO` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `INICIO` DATE,
  `FIM` DATE,
  `DURACAO` DECIMAL(4,0)
);

CREATE TABLE `CENARIO_PREVISAO` (
  `IDT_CENARIO` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `IDT_MODELO` INT,
  `IDT_PERIODO` INT,
  `PARAMETRO` VARCHAR(80),
  `MAPE` DECIMAL(9,9),
  CONSTRAINT cenario_modelo_fk
    FOREIGN KEY (`IDT_MODELO`)
	REFERENCES `MODELO_PREVISAO` (`IDT_MODELO`)
    ON DELETE CASCADE,
  CONSTRAINT cenario_periodo_fk
    FOREIGN KEY (`IDT_PERIODO`)
	REFERENCES `PERIODO_PREVISAO` (`IDT_PERIODO`)
    ON DELETE CASCADE
);
commit;